---
title: "titanic kaggle"
# fn <- "2015-08-31-boosting-algo.Rmd"
# library(knitr) ; knit(fn)  # produces the md file
# pandoc(fn, format = "docx") # prodces the .docx file
# permalink: If you need your processed blog post URLs to be something other than the default /year/month/day/title.html then you can set this variable and it will be used as the final URL.
date: "2015 July"
tags:
- R
- model 
categories:
- rstat, titanic, kaggle
# published = false => Jekyll will not process the file. Else Rmd file appears as a blog with html file i.e. 2 posts.
published: false 
# output: ioslides_presentation  
output:
  #  html_document:
  # http://rmarkdown.rstudio.com/html_fragment_format.html
  # html_fragment - no title or author -  excl std hdr content . HTML within larger web sites (e.g. blogs).
  html_fragment: 
    toc: true
    # theme: united
    number_sections: true
    keep_md: false
  # rmarkdown::render(fn) # produces table of contents and united theme
  # render(fn, pdf_document()) # library(rmarkdown) ; # knit2html() 
fontsize: 12pt
layout: post
author: "ttmmghmm"
---


## titantic - kaggle
[Source blog]<https://github.com/wehrley/wehrley.github.io/blob/master/SOUPTONUTS.md>


```{r, define readData}
readData <- function(path.name, file.name, column.types, missing.types) {
  read.csv( url( paste(path.name, file.name, sep="") ), 
            colClasses=column.types,
            na.strings=missing.types )
}
```
```{r, get data}
Titanic.path <- "https://raw.github.com/wehrley/Kaggle_Titanic/master/"
train.data.file <- "train.csv"
test.data.file <- "test.csv"
missing.types <- c("NA", "")
train.column.types <- c('integer',   # PassengerId
                        'factor',    # Survived 
                        'factor',    # Pclass
                        'character', # Name
                        'factor',    # Sex
                        'numeric',   # Age
                        'integer',   # SibSp
                        'integer',   # Parch
                        'character', # Ticket
                        'numeric',   # Fare
                        'character', # Cabin
                        'factor'     # Embarked
)
test.column.types <- train.column.types[-2]     # # no Survived column in test.csv

```


You can also embed plots, for example:

```{r, read in data - https}
train.raw <- readData(Titanic.path, train.data.file, 
                      train.column.types, missing.types)
df.train <- train.raw
test.raw <- readData(Titanic.path, test.data.file, 
                     test.column.types, missing.types)
df.infer <- test.raw   
str(df.infer)
str(df.train)
```
```{r, echo= FALSE}
## map missing data by provided feature
require(Amelia)
missmap(df.train, main="Titanic Training Data - Missings Map", 
        col=c("yellow", "black"), legend=FALSE)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}
barplot(table(df.train$Survived),
        names.arg = c("Perished", "Survived"),
        main="Survived (passenger fate)", col="black")
barplot(table(df.train$Pclass), 
        names.arg = c("first", "second", "third"),
        main="Pclass (passenger traveling class)", col="firebrick")
barplot(table(df.train$Sex), main="Sex (gender)", col="darkviolet")
hist(df.train$Age, main="Age", xlab = NULL, col="brown")
barplot(table(df.train$SibSp), main="SibSp (siblings + spouse aboard)", 
        col="darkblue")
barplot(table(df.train$Parch), main="Parch (parents + kids aboard)", 
        col="gray50")
hist(df.train$Fare, main="Fare (fee paid for ticket[s])", xlab = NULL, 
     col="darkgreen")
barplot(table(df.train$Embarked), 
        names.arg = c("Cherbourg", "Queenstown", "Southampton"),
        main="Embarked (port of embarkation)", col="sienna")
```


## test ggvis
```{r}
library(ggvis)
library(dplyr)
```

###  Scatterplots
We'll use the built-in mtcars data set, and look at two columns of interest, mpg, and wt:

````{r, plto cars}
# The first few rows of mtcars
head(mtcars)
#>                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
#> Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
#> Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
#> Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
#> Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
#> Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
#> Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1
mtcars %>% ggvis(~wt, ~mpg) %>% layer_points()
```

