---
title: "test"
output: html_document
---

test


```{r}
suffix2expiry <- function(suffix, root='VX', ...) {
  if (exists(paste('suffix2expiry',root,sep="."))) {
    do.call(paste('suffix2expiry',root,sep='.'),list(suffix, ...))
  } else {
    warning(paste(root, 'is not and available suffix2expiry
                  method; using "VX" instead'))
    do.call('suffix2expiry.VX',list(suffix, ...))
  }
}

#' Get the expiration date of an instrument given it's primary_id
#'
#' \code{primary2expiry} is basically a wrapper for
\code{\link{suffix2expiry}}.  It uses
#' \code{\link[FinancialInstrument]{parse_id}} to split the
\code{primary_id} into rood_id and suffix_id.
#' then it calls the appropriate \code{\link{suffix2expiry}} method.
#'
#' \code{suffix2expiry} is a generic-like function.  There should be a
method defined
#' the "root_id".  Currently, written methods include "VX", "ES" (and
aliases "YM", "NQ").
#' There are links to methods help pages in the seealso section.
#'
#' @param primary_id character string.  Primary identifier of the instrument
#' @param root character string. root symbol like "ES" or "VX" (NULL)
#' @param silent silence warnings? (TRUE)
#' @param suffix character string that indicates expiration month and
year (and, for options, right and strike).
#' See \code{\link[FinancialInstrument]{parse_suffix}} for examples of
acceptable formats.
#' @param ... any arguments to be passed to the \code{suffix2expiry} method
#' @return expiration Date
#' @seealso \code{\link{suffix2expiry.VX}}, \code{\link{suffix2expiry.ES}}
#' @aliases primary2expiry, suffix2expiry
#' @author gsee
#' @examples
#' primary2expiry("ESU1")
#' suffix2expiry('V11', root='VX')
#' @export
#' @rdname primary2expiry
primary2expiry <- function(primary_id, root=NULL, silent=TRUE) {
  idlist <- parse_id(primary_id, silent=silent)
  if (is.null(root)) root <- idlist$root
  do.call(paste("suffix2expiry",root,sep='.'),
          list(suffix=idlist$suffix, silent=silent))
}
```

```{r}
library(qmao)
library(timeDate) # for holidayNYSE
setSymbolLookup(VX='cfe')
vx <- getSymbols('VX',Month=1:12,Year=2007:2011)

plot.zoo(term.structure(vx, seq(20, 200, 20)), screens=1, col=rainbow(10))
```
