---
title: "sample a  line from a file"
date: "2015 July"
output: html_document
layout: post
author: "ttmmghmm"
---

# http://www.regexprn.com/2008/11/read-random-line-in-large-file-in.html

```{r}
# #!/usr/bin/env python
# import random, sys

# file = open(sys.argv[1])
# count = 0
# to_print = cur = file.readline()
# while cur:
# cur = file.readline()
# count += 1
# if random.randint(0,count) == 0: # 1/count chance to replace
# to_print = cur
# 
# print to_print[:-1] # Remove new line at end 
```

# See [http://r.789695.n4.nabble.com/Fast-way-to-determine-number-of-lines-in-a-file-td1472962.html]
```{r}
library(dplyr)
pathToFilename <- R.home()  %>% 
  list.files(full.names = TRUE, patt = ".*txt$", recur = TRUE, include.dirs = TRUE)
pathToFilename %>% head
bigFiles <- pathToFilename %>% 
  sapply(function(xx) file.info(xx)$size) %>%
  sort(decr = TRUE) %>%
  head(n = 10)
bigFiles
(oneFile <- names(bigFiles[2]))
tmp <- oneFile %>% readChar(file.info(.)$size)
# count how many "\n" there are in the output. e.g.
length(gregexpr("\n", tmp)[[1L]])

```

```{r, eval = FALSE}
# http://r.789695.n4.nabble.com/Fast-way-to-determine-number-of-lines-in-a-file-td1472962.html


#  countLines() in the R.utils package 
pathname <- system.file("NEWS", package="R.utils");
n <- countLines(pathname);
n2 <- length(readLines(pathname));
stopifnot(n == n2);


if(.Platform$OS.type=="windows"){ 
  system.time({ 
    cmd<-system(paste("/RTools/bin/wc -l","much_data.bin"), intern=TRUE) 
    cmd<-strsplit(cmd, " ")[[1]][1] 
    }) 
 } 


datafile = "../data/myfile.csv"
> read.csv.sql(datafile,"select count(*) from file")


testconn <- file("xyzxyz.csv.bz2", open="r") 
csize <- 10000 
nolines <- 0 
while((readnlines <- length(readLines(testconn,csize))) >0 ) nolines 
<- nolines+readnlines 
close(testconn) 
nolines 

tmp <- readChar(pathToFilename, file.info(pathToFilename)$size)
#and then count how many "\n" there are in the output. e.g.
length(gregexpr("\n",tmp)[[1L]])
#This above is 3x faster then countLines. I tested on different files with 2000 to 10000 rows
```