---
title: "sample a  line from a file"
output: html_document
---

# http://www.regexprn.com/2008/11/read-random-line-in-large-file-in.html

```{r}
# #!/usr/bin/env python
# import random, sys

# file = open(sys.argv[1])
# count = 0
# to_print = cur = file.readline()
# while cur:
# cur = file.readline()
# count += 1
# if random.randint(0,count) == 0: # 1/count chance to replace
# to_print = cur
# 
# print to_print[:-1] # Remove new line at end 
```

# See [http://r.789695.n4.nabble.com/Fast-way-to-determine-number-of-lines-in-a-file-td1472962.html]
```{r}
library(dplyr)
pathToFilename <- R.home()  %>% 
  list.files(full.names = TRUE, patt = ".*txt$", recur = TRUE, include.dirs = TRUE)
pathToFilename %>% head
bigFiles <- pathToFilename %>% 
  sapply(function(xx) file.info(xx)$size) %>%
  sort(decr = TRUE) %>%
  head(n = 10)
bigFiles
(oneFile <- names(bigFiles[2]))
tmp <- oneFile %>% readChar(file.info(.)$size)
# count how many "\n" there are in the output. e.g.
length(gregexpr("\n", tmp)[[1L]])

```

You can also embed plots, for example:

```{r, echo=FALSE}
plot(cars)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
